[tool.poetry]
name = "ed25519-python-golang"
version = "0.1.0"
description = ""
authors = ["owenlo <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
PyNaCl = "^1.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
